export const GENRE: Record<
  "movie" | "tv",
  Array<{ id: number; genre: string }>
> = {
  movie: [
    { id: 12, genre: "Adventure" },
    { id: 14, genre: "Fantasy" },
    { id: 16, genre: "Animation" },
    { id: 18, genre: "Drama" },
    { id: 27, genre: "Horror" },
    { id: 28, genre: "Action" },
    { id: 35, genre: "Comedy" },
    { id: 36, genre: "History" },
    { id: 37, genre: "Western" },
    { id: 53, genre: "Thriller" },
    { id: 80, genre: "Crime" },
    { id: 99, genre: "Documentary" },
    { id: 878, genre: "Science Fiction" },
    { id: 9648, genre: "Mystery" },
    { id: 10402, genre: "Music" },
    { id: 10749, genre: "Romance" },
    { id: 10751, genre: "Family" },
    { id: 10752, genre: "War" },
    { id: 10770, genre: "TV Movie" },
  ],
  tv: [
    { id: 16, genre: "Animation" },
    { id: 18, genre: "Drama" },
    { id: 35, genre: "Comedy" },
    { id: 37, genre: "Western" },
    { id: 80, genre: "Crime" },
    { id: 99, genre: "Documentary" },
    { id: 9648, genre: "Mystery" },
    { id: 10751, genre: "Family" },
    { id: 10759, genre: "Action & Adventure" },
    { id: 10762, genre: "Kids" },
    { id: 10763, genre: "News" },
    { id: 10764, genre: "Reality" },
    { id: 10765, genre: "Sci-Fi & Fantasy" },
    { id: 10766, genre: "Soap" },
    { id: 10767, genre: "Talk" },
    { id: 10768, genre: "War & Politics" },
  ],
};
