import React from 'react';
import Card from '../../UI/Card';

const PrivacyPolicy: React.FC = () => {
    return (
        <Card className="p-6 m-2">
            <p className='text-3xl font-bold'>Privacy Policy</p>
            Updated at 2023-02-11
            <p>
                Bingenow ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal collected, used, and disclosed by Bingenow.
                This Privacy Policy applies to our website, https://bingenow.net, and its associated subdomains (collectively, our "Sen accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, e of your personal information as described in this Privacy Policy and our Terms of Service.
            </p>
            <br/>
            <p className='text-xl font-bold'>Definitions and key terms</p>
            To help explain things as clearly as possible in this privacy policy, every time any of these terms are referenced, are strictly defined as:
            <ul className='mx-6 list-disc'>
                
                
                <li><b>Cookie</b>: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
                    provide analytics, remember information about you such as your language preference or login information.
                </li>
                <li>
                    <b>Company</b>: when this policy mentions "Company","we," "us," or "our," it refers to Bingenow that is responsible for your
                    information under this Privacy Policy.
                </li>
                <li><b>Country</b>: where Bingenow or the owners/founders of Bingenow are based, in this case is India.</li>
                <li><b>Customer</b>: refers to the company. organization or person that signs up to use the Bingenow Service to manage the
                    relationships with your consumers or service users.</li>
                <li><b>Device</b>: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Bingenow and use the services.</li>
                <li><b>IP address</b>: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks.
                    An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><b>Personnel</b>: refers to those individuals who are employed by Bingenow or are under contract to perform a service on behalf of one of the parties.</li>
                <li><b>Personal Data</b>: any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person.</li>
                <li><b>Service</b>: refers to the service provided by Bingenow as described in the relative terms (if available) and on this platform.</li>
                <li><b>Third-party service</b>: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><b>Website</b>: Bingenow's site, which can be accessed via this URL: https://bingenow.net.</li>
                <li><b>You</b>: a person or entity that is registered with Bingenow to use the Services.</li>
            </ul>

            <br/>
            <p className='text-xl font-bold'>What Information Do We Collect?</p>
            We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, re or fill out a form.
            <ul className='mx-6 list-disc'>
                <li>Name / Username</li>
                <li>Email Addresses</li>
            </ul>

            <br/>
            <p className='text-xl font-bold'>How Do We Use The Information We Collect?</p>
            Any of the information we collect from you may be used in one of the following ways:
            <ul className='mx-6 list-disc'>
            
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our service (we continually strive to improve our service offerings based on the information and feedbac from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service reque:support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
            </ul>
            <br/>

            <p className='text-xl font-bold'>
                How Do We Use Your Email Address?
            </p>
            <p>
                By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time. you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
            </p>
            <br/>

            <p className='text-xl font-bold'>Is the information collected through our service secure?</p>
            <p>
                We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encrypon systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
            </p>

            <br/>
            <p className='text-xl font-bold'>Sale of Business</p>
            <p>
                We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which tr Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
            </p>

            <br/>
            <p className='text-xl font-bold'>How Long Do We Keep Your Information?</p>
            <p>We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need t use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.
            </p>

            <br/>
            <p className='text-xl font-bold'>How Do We Protect Your Information?</p>
            <p>
                We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
            </p>

            <br/>
            <p className='text-xl font-bold'>Governing Law</p>
            <p>The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.
            </p>

            <br/>
            <p className='text-xl font-bold'>
                Your Consent</p>
            <p>By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.
            </p>

            <br/>
            <p className='text-xl font-bold'>Links to Other Websites</p>
            <p>
                This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us.
                We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
            </p>

            <br/>
            <p className='text-xl font-bold'>Kids' Privacy</p>
            <p>
                We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from our servers.
            </p>

            <br/>
            <p className='text-xl font-bold'>Changes To Our Privacy Policy
            </p>
            <p>
                If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.
            </p>

            <br/>
            <p className='text-xl font-bold'>Third-Party Services</p>
            <p>
                We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").
                You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any lablty or responsibilly jo you or any other person or entity for any Third-Party Services.
                Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.
            </p>

            <br/>
            <p className='text-xl font-bold'>Tracking Technologies</p>
            <ul className='mx-6 list-disc'>
                <li>	Local Storage
                    Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage,
                    similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.
                </li>
            </ul>

            <br/>
            <p className='text-xl font-bold'>Contact Us</p>
            <ul className='mx-6 list-disc'>Don't hesitate to contact us if you have any questions.
                <li><b>Via Email</b>: prajwalkulkarni@protonmail.com</li>
            </ul>

        </Card>
    )
}

export default PrivacyPolicy;